apiVersion: v1
kind: ConfigMap
metadata:
  name: sneakertail-config
  namespace: sneakertail
data:
  NODE_ENV: "production"
  DB_SSL: "true"
  CATALOG_SERVICE_URL: "http://catalog-service:4001"
  CATALOG_API_URL: "/catalog-api"
  CART_API_URL: "/cart-api"
