apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: sneakertail
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: muhammedsinanust/sneakertail-frontend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          env:
            - name: CATALOG_API_URL
              valueFrom:
                configMapKeyRef:
                  name: sneakertail-config
                  key: CATALOG_API_URL
            - name: CART_API_URL
              valueFrom:
                configMapKeyRef:
                  name: sneakertail-config
                  key: CART_API_URL
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
