apiVersion: v1
kind: Secret
metadata:
  name: sneakertail-db
  namespace: sneakertail
type: Opaque
stringData:
  DATABASE_URL: "postgres://pgadminuser:<postgres-password>@<postgres-fqdn>:5432/sneakertail?sslmode=require"
